language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install poetry
  - poetry install
script:
  - poetry run py.test --cov-report=xml --cov=.
  - poetry run bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN
